# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: user-deployment
#   labels:
#     app: user-service
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: user-service
#   template:
#     metadata:
#       labels:
#         app: user-service
#     spec:
#       containers:
#       - name: user-container
#         image: user-service:v1
#         imagePullPolicy: Never # Use local image
#         ports:
#         - containerPort: 5000
#         env:
#         - name: DB_HOST
#           value: "user-db-service"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-service
# spec:
#   selector:
#     app: user-service
#   ports:
#     - protocol: TCP
#       port: 8080 # External Port
#       targetPort: 5000 # Container Port
#   type: NodePort # Allows external access


apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-container
        image: user-service:v1
        imagePullPolicy: Never # Use local image
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:pass@user-db-service:5432/userdb"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: NodePort
